# Generated by Django 5.1.1 on 2024-10-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_gay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('eggs_amount', models.IntegerField(default=0)),
                ('eggs_per_hour', models.FloatField(default=0.0)),
                ('current_hero', models.CharField(max_length=255)),
                ('bought_heros', models.TextField()),
                ('friends', models.TextField()),
                ('current_energy', models.IntegerField(default=100)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gay',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
