# Generated by Django 5.1.1 on 2024-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_guests_delete_gay_delete_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='bought_heros',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='current_energy',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='current_hero',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='eggs_amount',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='eggs_per_hour',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='name',
        ),
        migrations.AddField(
            model_name='guests',
            name='all_heros',
            field=models.TextField(default='Hobo', verbose_name='All Heroes'),
        ),
        migrations.AddField(
            model_name='guests',
            name='egg_amm',
            field=models.IntegerField(default=0, verbose_name='Egg Amount'),
        ),
        migrations.AddField(
            model_name='guests',
            name='energy',
            field=models.IntegerField(default=5, verbose_name='Energy'),
        ),
        migrations.AddField(
            model_name='guests',
            name='hero_lvl',
            field=models.IntegerField(default=1, verbose_name='Hero Level'),
        ),
        migrations.AddField(
            model_name='guests',
            name='hero_uprise',
            field=models.IntegerField(default=1000, verbose_name='Hero Uprise'),
        ),
        migrations.AddField(
            model_name='guests',
            name='max_hero_lvl',
            field=models.IntegerField(default=1, verbose_name='Max Hero Level'),
        ),
        migrations.AddField(
            model_name='guests',
            name='nohero_uprise',
            field=models.IntegerField(default=0, verbose_name='No Hero Uprise'),
        ),
        migrations.AddField(
            model_name='guests',
            name='now_hero',
            field=models.CharField(default='Hobo', max_length=100, verbose_name='Current Hero'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='friends',
            field=models.TextField(blank=True, verbose_name='Friends'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.DateTimeField(verbose_name='Last Visit'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='tg_id',
            field=models.CharField(max_length=100, verbose_name='Telegram ID'),
        ),
    ]
