# Generated by Django 5.1.1 on 2024-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_guests_bought_heros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='11.02.2004', max_length=100, verbose_name='Last Visit'),
        ),
    ]
