# Generated by Django 5.1.1 on 2024-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='egg_amm',
            field=models.FloatField(default=0, verbose_name='Egg Amount'),
        ),
    ]
