# Generated by Django 5.1.1 on 2024-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_guests_egg_amm'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='pns_amm',
            field=models.FloatField(default=0, verbose_name='PNS Amount'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='24.10.2024, 18:25:10', max_length=100, verbose_name='Last Visit'),
        ),
    ]
