# Generated by Django 5.1.1 on 2024-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_guests_pns_amm_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='nickname',
            field=models.CharField(default='username', max_length=100, verbose_name='Nick'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='25.10.2024, 18:31:21', max_length=100, verbose_name='Last Visit'),
        ),
    ]
