# Generated by Django 5.1.1 on 2024-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_guests_nickname_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='use_case',
            field=models.IntegerField(default=0, verbose_name='Use Case'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='04.11.2024, 19:35:08', max_length=100, verbose_name='Last Visit'),
        ),
    ]
