# Generated by Django 5.1.1 on 2024-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_guests_use_case_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='friends',
            field=models.TextField(default=[], verbose_name='Friends'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='04.11.2024, 23:06:49', max_length=100, verbose_name='Last Visit'),
        ),
    ]
