# Generated by Django 5.1.1 on 2024-11-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_guests_friends_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='friends',
            field=models.TextField(blank=True, verbose_name='Friends'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='04.11.2024, 23:11:40', max_length=100, verbose_name='Last Visit'),
        ),
    ]
