# Generated by Django 5.1.1 on 2024-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_guests_friends_alter_guests_last_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFriendships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100, verbose_name='First Friend ID')),
                ('second', models.CharField(max_length=100, verbose_name='Second Friend ID')),
                ('type', models.CharField(max_length=50, verbose_name='Friendship Type')),
            ],
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='05.11.2024, 17:26:18', max_length=100, verbose_name='Last Visit'),
        ),
    ]
