# Generated by Django 5.1.1 on 2024-11-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_newfriendships_alter_guests_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='user_urls',
            field=models.TextField(default={'INST': 0, 'TG': 0, 'TT': 0, 'YouTube': 0}, verbose_name='Urls'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='07.11.2024, 22:08:00', max_length=100, verbose_name='Last Visit'),
        ),
    ]
