# Generated by Django 5.1.1 on 2024-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_guests_user_urls_alter_guests_last_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFriendships',
        ),
        migrations.AlterField(
            model_name='guests',
            name='last_visit',
            field=models.CharField(default='25.11.2024, 18:27:42', max_length=100, verbose_name='Last Visit'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='nickname',
            field=models.CharField(default='Введите имя', max_length=100, verbose_name='Nick'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='user_urls',
            field=models.TextField(default='{"TG": 0, "TT": 0, "INST": 0, "YouTube": 0}', verbose_name='Urls'),
        ),
    ]
